// Package users provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package users

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// User defines model for User.
type User struct {
	Balance     int    `json:"balance"`
	DisplayName string `json:"displayName"`
	Email       string `json:"email"`
	Role        string `json:"role"`
}

// SignUpUserJSONBody defines parameters for SignUpUser.
type SignUpUserJSONBody User

// SignUpUserJSONRequestBody defines body for SignUpUser for application/json ContentType.
type SignUpUserJSONRequestBody SignUpUserJSONBody
