// Package users provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package users

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// User defines model for User.
type User struct {
	Balance     float32 `json:"balance"`
	DisplayName string  `json:"displayName"`
	Email       string  `json:"email"`
	Role        string  `json:"role"`
	Uuid        string  `json:"uuid"`
}

// UserSignIn defines model for UserSignIn.
type UserSignIn struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// UserSignUp defines model for UserSignUp.
type UserSignUp struct {
	Balance     float32 `json:"balance"`
	DisplayName string  `json:"displayName"`
	Email       string  `json:"email"`
	Password    string  `json:"password"`
	Role        string  `json:"role"`
}

// SignInUserJSONBody defines parameters for SignInUser.
type SignInUserJSONBody UserSignIn

// SignUpUserJSONBody defines parameters for SignUpUser.
type SignUpUserJSONBody UserSignUp

// SignInUserJSONRequestBody defines body for SignInUser for application/json ContentType.
type SignInUserJSONRequestBody SignInUserJSONBody

// SignUpUserJSONRequestBody defines body for SignUpUser for application/json ContentType.
type SignUpUserJSONRequestBody SignUpUserJSONBody
