version: '3'
services:
  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
    working_dir: /web
    volumes:
      - ./web:/web
      - /web/node_modules/
    ports:
      - 127.0.0.1:3000:3000

  products-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/products
    ports:
      - 127.0.0.1:3003:$PORT
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: http
    depends_on:
      - firestore

  products-grpc:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/products
    ports:
      - 127.0.0.1:3030:$PORT
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: grpc
    depends_on:
      - firestore


#   trainer-http:
#     build:
#       context: docker/app
#     volumes:
#       - ./internal:/internal
# #      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
#     working_dir: /internal/trainer
#     ports:
#       - "127.0.0.1:3000:$PORT"
#     env_file:
#       - .env
#     environment:
#       SERVER_TO_RUN: http
#     depends_on:
#       - firestore

#   trainer-grpc:
#     build:
#       context: docker/app
#     volumes:
#       - ./internal:/internal
# #      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
#     working_dir: /internal/trainer
#     ports:
#       - "127.0.0.1:3010:$PORT"
#     env_file:
#       - .env
#     environment:
#       SERVER_TO_RUN: grpc
#     depends_on:
#       - firestore

  orders-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/orders
    ports:
      - 127.0.0.1:3002:$PORT
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: http
    depends_on:
      - firestore

  orders-grpc:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/orders
    ports:
      - 127.0.0.1:3020:$PORT
    env_file:
      - .env
    environment:
      SERVER_TO_RUN: grpc
    depends_on:
      - firestore


#   trainings-http:
#     build:
#       context: docker/app
#     volumes:
#       - ./internal:/internal
# #      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
#     working_dir: /internal/trainings
#     ports:
#       - "127.0.0.1:3001:$PORT"
#     env_file:
#       - .env
#     depends_on:
#       - firestore
    
  
  checkouts-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/checkouts
    ports:
      - 127.0.0.1:3001:$PORT
    env_file:
      - .env
    depends_on:
      - firestore

  users-http:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/users
    ports:
      - 127.0.0.1:3004:$PORT
    environment:
      SERVER_TO_RUN: http
    env_file:
      - .env
    depends_on:
      - firestore

  users-grpc:
    build:
      context: docker/app
    volumes:
      - ./internal:/internal
#      - ./service-account-file.json:$SERVICE_ACCOUNT_FILE
    working_dir: /internal/users
    ports:
      - 127.0.0.1:3040:$PORT
    environment:
      SERVER_TO_RUN: grpc
    env_file:
      - .env
    depends_on:
      - firestore

  firestore:
    image: karhoo/firestore-emulator:0.3.2
    env_file:
      - .env
    ports:
      - 127.0.0.1:8787:8787
      - 127.0.0.1:4000:4000
    restart: unless-stopped

  firestore-component-tests:
    image: karhoo/firestore-emulator:0.3.2
    env_file:
      - .env
    ports:
      - 127.0.0.1:8788:8787
    restart: unless-stopped

  mysql:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 127.0.0.1:3306:3306
    restart: unless-stopped
