// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package ports

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateOrder defines model for CreateOrder.
type CreateOrder struct {
	ProductUuids []string `json:"productUuids"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// Order defines model for Order.
type Order struct {
	ExpiresAt    time.Time `json:"expiresAt"`
	ProductUuids []string  `json:"productUuids"`
	ProposedTime time.Time `json:"proposedTime"`
	Status       string    `json:"status"`
	UserUuid     string    `json:"userUuid"`
	Uuid         string    `json:"uuid"`
}

// Orders defines model for Orders.
type Orders struct {
	Trainings *[]Order `json:"trainings,omitempty"`
}

// GetOrderParams defines parameters for GetOrder.
type GetOrderParams struct {
	// The order uuid.
	OrderUuid string `json:"orderUuid"`
}

// CreateOrderJSONBody defines parameters for CreateOrder.
type CreateOrderJSONBody CreateOrder

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody CreateOrderJSONBody
