// Package checkouts provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package checkouts

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Checkout defines model for Checkout.
type Checkout struct {
	Notes        string    `json:"notes"`
	OrderUuid    string    `json:"orderUuid"`
	ProposedTime time.Time `json:"proposedTime"`
	UserUuid     string    `json:"userUuid"`
	Uuid         string    `json:"uuid"`
}

// Checkouts defines model for Checkouts.
type Checkouts []Checkout

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// NewCheckout defines model for NewCheckout.
type NewCheckout struct {
	Notes        string    `json:"notes"`
	OrderUuid    string    `json:"orderUuid"`
	ProposedTime time.Time `json:"proposedTime"`
}

// CreateCheckoutJSONBody defines parameters for CreateCheckout.
type CreateCheckoutJSONBody NewCheckout

// CreateCheckoutJSONRequestBody defines body for CreateCheckout for application/json ContentType.
type CreateCheckoutJSONRequestBody CreateCheckoutJSONBody
