openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Ecommerce shop checkout
  description: This is Openapi generator server for generate ecommerce shop checkout api
  contact:
    name: giaphm
    url: http://github.com/giaphm
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
security:
  - bearerAuth: []
paths:
  /checkouts:
    get:
      operationId: getCheckouts
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Checkouts'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      operationId: createCheckout
      requestBody:
        description: todo
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCheckout'
      responses:
        '204':
          description: todo
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /checkouts/user-checkouts/{userUuid}:
    get:
      operationId: getUserCheckouts
      parameters:
        - in: path
          name: userUuid
          schema:
            type: string
          required: true
          description: The user uuid.
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Checkouts'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Checkout:
      type: object
      required: [uuid, userUuid, orderUuid, notes, proposedTime]
      properties:
        uuid:
          type: string
          format: uuid
        userUuid:
          type: string
          format: uuid
        orderUuid:
          type: string
          format: uuid
        notes:
          type: string
          example: "Ship asap please!"
        proposedTime:
          type: string
          format: date-time

    Checkouts:
      type: array
      items:
        $ref: '#/components/schemas/Checkout'

    NewCheckout:
      type: object
      required: [orderUuid, notes, proposedTime]
      properties:
        orderUuid:
          type: string
          format: uuid
        notes:
          type: string
          example: "Ship asap please!"
        proposedTime:
          type: string
          format: date-time

    Error:
      type: object
      required:
        - slug
        - message
      properties:
        slug:
          type: string
        message:
          type: string
